# Generated by Django 3.2.9 on 2021-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthDelimiter', models.CharField(max_length=20)),
                ('birthDay', models.SmallIntegerField()),
                ('birthMonth', models.SmallIntegerField()),
                ('birthYear', models.SmallIntegerField()),
                ('birthPlace', models.CharField(max_length=50)),
                ('deathDelimiter', models.CharField(max_length=20)),
                ('deathDay', models.SmallIntegerField()),
                ('deathMonth', models.SmallIntegerField()),
                ('deathYear', models.SmallIntegerField()),
                ('deathPlace', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
