# Generated by Django 3.2.9 on 2021-11-29 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0004_auto_20211124_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='art',
            field=models.FileField(default='media/3.png', upload_to='media'),
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_contributions', to=settings.AUTH_USER_MODEL)),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='boards.saint')),
            ],
        ),
        migrations.CreateModel(
            name='Miracle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miracle_contributions', to=settings.AUTH_USER_MODEL)),
                ('performedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miracles', to='boards.saint')),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('artist', models.CharField(max_length=70)),
                ('creationDate', models.DateField(null=True)),
                ('uploadedOn', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='')),
                ('depicting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='boards.saint')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_contributions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
