# Generated by Django 3.2.9 on 2021-11-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20211129_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='art',
            field=models.FileField(default='settings.MEDIA_ROOT/3.png', upload_to='settings.BASE_DIR/media/'),
        ),
    ]
