# Generated by Django 3.2.9 on 2021-11-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_saint_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='art',
            field=models.FileField(default='unknown.png', upload_to=''),
        ),
    ]
